### ISSUE TITLE
DNA import/link for strategic cruisers

### ISSUE THREAD

**Issue by Bierkof** [osmium-org/osmium#100]
Loadout links with DNA string or importing the loadouts using DNA string doesnt work for the strategic cruisers. The subsystem modules are not loaded, the modules are red and the calculations are defective.

How to reproduce the bug:
- try any tech 3 DNA loadout link (from zkillboard.com for example):
http://o.smium.org/loadout/dna/29988:31055;2:12058;1:29981;1:11269;1:30098;1:10190;1:3082;6:18807;1:448;1:1978;1:29001;1:14061;1:30149;1:31059;1:23025;72:18768;1:30056;1:30128;1:2048;1:20353;1:2488;5::
- or export as DNA any existing tech 3 ship loadout and try to import it afterwards

**Comment by Artefact2** [comment]
Partial fix in 1a5de30.

**Comment by Artefact2** [comment]
Cosmetic slot issue fixed in b19d117. Will be deployed on Tetroxide for v0.14.5 or v0.15.0.
