### ISSUE TITLE
when viewing fit of T3 it shows all slots as 0 (all modules turned red)

### ISSUE THREAD

**Issue by Tetlanesh** [osmium-org/osmium#102]
when viewing fit of T3 it shows all slots as 0 (all modules turned red). Using "show module info" on any subsystem fixed problem. This resurfaces after reloading page (opening link again in general)

Example fit: https://o.smium.org/loadout/private/32975/4553481695373819904

**Comment by Artefact2** [comment]
Already fixed in b19d1176a94d8e5b1066cd5330116b69999aaf87. Will be in 0.13.5 or 0.14.0.

**Comment by Artefact2** [comment]
Backported in ee47233b831430479502f72d86a10ea9ece29d94. You will have to clear your cache to see the effects.

**Comment by Tetlanesh** [comment]
Seems to work, thnx
