### ISSUE TITLE
Support Persona

### ISSUE THREAD

**Issue by Artefact2** [osmium-org/osmium#11]
Benefits:
- Simpler registration
- Password reset is no longer our problem
- Gives us an email address to potentially contact the user in case of emergency

Issues:
- Dosen't play nice with NoScript
- Requires JS and a recent-ish browser
- Reliance on Mozilla
- ~~How to handle old accounts? Force them to use Persona, or still allow legacy login and registration?~~
- ~~What would be the accountnames/passwordhashes of Persona accounts (make up random ones or allow NULL values in the schema)?~~

**Comment by petsagouris** [comment]
Unfortunately Persona has been [discontinued](https://developer.mozilla.org/en-US/docs/Archive/Mozilla/Persona):

> On November 30th, 2016, Mozilla shut down the persona.org services. Persona.org and related domains will soon be taken offline.
> For more information, see this guide to migrating your site away from Persona:
> https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers

**Comment by Artefact2** [comment]
Yeah, SSO mostly render this issue moot. Closing.

**Comment by Artefact2** [comment]
Yeah, SSO rendered this issue moot. Closing.
