### ISSUE TITLE
After delete refirect to profile page

### ISSUE THREAD

**Issue by CincyMattr** [osmium-org/osmium#126]
After deleting a fit redirected to home page, would be nice to redirect to your profile. Would make deleting fits easier. 

https://o.smium.org/profile/12345 and not https://o.smium.org/

**Comment by Artefact2** [comment]
Good idea, makes sense. Although, ideally we want to have a way to do batch operations on loadouts you can edit (ie mass-delete, mass-rename, mass-retag, etc…) so this could tie into that.

**Comment by Artefact2** [comment]
Partially fixed in b30adf4. Created new issue #160 for batch operations.
