### ISSUE TITLE
Osmium Fitting Tool small issue 

### ISSUE THREAD

**Issue by Snorrsen** [osmium-org/osmium#129]
Hi,

There is some little issue with the Warp Scrambler II module.
The fitting tool says it needs Porpulsion Jamming IV to be operational, in fact it only needs Propulsion Jamming II.

Best Regards!

**Comment by Artefact2** [comment]
Does it really? http://o.smium.org/db/type/448#r

Not sure what you mean. Can you tell us how to reproduce the issue?

**Comment by Snorrsen** [comment]
Hi,

i just tested it again, seems like i failed. I fitted some ship with 
Stasis Webifier II and Warp Scrambler II. It just said "Propulsion 
Jamming IV required by Warp Scrambler II, Stasis Webifier II". Seems 
like it just picks the highest skill needed.
Im sorry for the inconvenience.

Kind Regards

Am 23.01.2016 um 19:39 schrieb Romain D.:
