### ISSUE TITLE
Cloak CPU requirement reduction missing for endurance

### ISSUE THREAD

**Issue by Nothing4You** [osmium-org/osmium#130]
Hey there,

check out this example: https://o.smium.org/loadout/private/61255/8902048783068561408

Set it to All V and it shows 2.51 over the limit on CPU (100.7%).

Since the person who gave this fitting to me told me he could use it without any implants, I tested this in pyfa for comparison, where it shows perfectly fine (337.5 / 350 CPU @ 96.43%).

After testing a bit it seems that the problem is that the `50 %reduction in Cloaking Devices CPU requirement` is not applied.

**Comment by Artefact2** [comment]
Can't reproduce the issue as of today. Please reopen issue if the bug is still there.
