### ISSUE TITLE
Broken links for API creation

### ISSUE THREAD

**Issue by mrnsnp** [osmium-org/osmium#134]
Add EVE character from API

You can create an API key here: https://support.eveonline.com/api/Key/CreatePredefined/33554456

Above link sends me to:
https://support.eveonline.com/api/Key/CreatePredefined/33554456?flash_digest=660ce14bb18ce0cfe9d65a6c656bf44325854ebe

CCP's this page no longer exists.

By chance, could you just list what is needed for osmium to run properly in  the API, but keep your predefined osmium key generator for security.

**Comment by Artefact2** [comment]
Fixed in 0e4aa54. Thanks for reporting the issue, and shame on CCP for not redirecting the old links.

> By chance, could you just list what is needed for osmium to run properly in the API, but keep your predefined osmium key generator for security.

That's already the case, just read the page.
