### ISSUE TITLE
Remote Sensor Boosters / Tracking Computers cannot be applied

### ISSUE THREAD

**Issue by Nothing4You** [osmium-org/osmium#135]
Hello,

I'm unable to use the following fit with projected modules on other ships.

When I add it for projected effects it doesn't show the modules to project them on my local ship.

This must have changed recently as I have done that for other fits in the past just fine.

![Remote Badger](https://i.imgur.com/3qsr0k1.png)
## Badger loadout
# Remote
# Presets
### Medium slots
- Remote Sensor Booster II
- Remote Sensor Booster II
- Remote Sensor Booster II
- Remote Sensor Booster II
- Remote Tracking Computer II
- Remote Tracking Computer II
#### Default charge preset
- Optimal Range Script
- Tracking Speed Script
- Scan Resolution Script
- Scan Resolution Script
- Scan Resolution Script
- Scan Resolution Script
# Other
- Designed for: March 2016 (march2016-10; build 1017895)
- Tags: (none)
- Damage profile: Uniform (EM: 25%, Explosive: 25%, Kinetic: 25%, Thermal: 25%)

---

```
BEGIN gzCLF BLOCK
eJzNkM1uwjAQhF9l616gpMXOD8S5Veq5lSg3wsFKNmCR2JHjICHEu9cJUKVIrTjWp/Xs+PPu
HElWFs97NI3UiiTMc3eJyg4kyuYxjzxSoRW5sIIkR2KlLZEk5F1bwD0qMFhpi+XhAUavptIG
JrA0IttJtRnDqNBmNyYeybHJjKxtDyZPy61soNQi160FVwrojKCLb3H1GAWMxetROr1I6bRX
FqHDGtzLbkgIxy9PqUrVXcSQ++HsB7FXFvMhce6IbuDMoOimdXt36362ygM/go/Mgk9ZBJQl
QZD4AUyoO+TkkWYr6z6hQ40yJ8ksjJ1aG2zQNiRZHS+1ElVHfMNCtKWFs+h+rHTelnh2XhmM
z0I3y1aYzU3H55Sx0/rk/Tuzz+hv5phzfreZU9qR19f2MMnOQD1yE+XZd030/DY3WuEf8ff9
wZMvdtf/0w==
END gzCLF BLOCK
```

**Comment by Artefact2** [comment]
This is fixed in libdogma [e8532f9](/osmium-org/libdogma/commit/e8532f941cf94f1f9b42ec8300ac080694c4b5b1), although this will create a lot of false positives.

**Comment by Artefact2** [comment]
Oh, and manually clear all your cache to see the change.

**Comment by Nothing4You** [comment]
Thanks, any idea when this will go live on o.smium.org?

**Comment by Artefact2** [comment]
It as already live. As I've already said, clear your cache to see the change.

**Comment by Nothing4You** [comment]
Weird, in firefox it doesn't even show up after clearing my cache, in chrome it shows all the modules.

**Comment by Nothing4You** [comment]
I just found out why it didn't work: It needs localStorage.clear() in firefox to get that stuff cleared.
