### ISSUE TITLE
Add market prices to the auto comparison page for modules

### ISSUE THREAD

**Issue by cdanis** [osmium-org/osmium#136]
When looking at a module variations comparison page like this:
https://o.smium.org/db/comparevariations/21484/auto
it'd be awesome to have some sort of aggregate market price (Jita? average of several market hubs?) there.  Even just an approximation -- knowing that T2 costs X mil, meta costs Y mil, this faction costs ZZ million, etc.

Thanks!

**Comment by Artefact2** [comment]
Duplicate of #56.
