### ISSUE TITLE
energized adaptive nano membrane II is -23%

### ISSUE THREAD

**Issue by glelouet** [osmium-org/osmium#145]
and it shows -20%
https://o.smium.org/db/comparevariations/11269/auto

**Comment by Artefact2** [comment]
What are your armor compensation skills?

**Comment by glelouet** [comment]
I'm not logged in so I guess it does not use my char.

**Comment by glelouet** [comment]
I logged in and it still shows -20% while Eve shows -23%

**Comment by glelouet** [comment]
my armor compensation skills are at 3, which means 20% *1.15 = 23. Comes from me.
