### ISSUE TITLE
Polarized weapons result in zero resistances

### ISSUE THREAD

**Issue by Globulino** [osmium-org/osmium#153]
1. create new loadout (e.g. Hurricane)
2. add a polarized weapon (e.g. Polarized 425mm AutoCannon)
3. defense window shows 0% resistances (shield to structure, em to exp)

**Comment by Artefact2** [comment]
Duh.

> Polarized weapons offer extremely good primary stats, but come with the cost of completely negating all resistances on a ship if fitted.
