### ISSUE TITLE
Cannot view module info unless editing

### ISSUE THREAD

**Issue by jprupp** [osmium-org/osmium#186]
When viewing a fitting (but not editing) and trying to get information about a module I get an error. When I am editing a fitting it works as expected.

**Comment by fletom** [comment]
> Could not show info: error (Bad Request). Try refreshing the page and report if the problem persists.

this error right?

+1

**Comment by jprupp** [comment]
> Could not show info: error (Bad Request). Try refreshing the page and report if the problem persists.

It fails no matter how many times I refresh the page.

**Comment by Artefact2** [comment]
I can reproduce the issue as well. I think it's related to Tetroxide, not an actual bug. This will be fixed soon.
