### ISSUE TITLE
There is no option to delete a private loadout

### ISSUE THREAD

**Issue by yuriy-yarosh** [osmium-org/osmium#187]
So, by accident I've imported tons of loadouts, and I can't find any way to delete 'em.
And by a coincidence it turns out that loadout deletion is "internal" for a reason unknown.
That is really missconvinient. I see no reason why you shouldn't allow complete CRUD actions for the loadout authors.

**Comment by Artefact2** [comment]
View loadout.
Click meta tab.
Click "Delete this loadout" link under "Actions".
