### ISSUE TITLE
When logging in with ccp credentials 

### ISSUE THREAD

**Issue by eskwire** [osmium-org/osmium#188]
I got the message http://imgur.com/8t9jOQE cant log any more re try and it still dont work.

**Comment by Artefact2** [comment]
Works fine for me.

Have you used Osmium with this character before? Have you read the error message?

**Comment by eskwire** [comment]
Nop firts time with this toon.

**Comment by eskwire** [comment]
Where can I see the error message, I only get that image that I post.
