### ISSUE TITLE
JavaScript not loading

### ISSUE THREAD

**Issue by jprupp** [osmium-org/osmium#189]
HTTPS site on Firefox on Windows not loading JavaScript at the moment.

**Comment by jprupp** [comment]
This appears on the browser console:

> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://o.smium.org https://cdnjs.cloudflare.com”).

**Comment by Artefact2** [comment]
Thanks for reporting the issue. Something is wrong with the minifier and I have disabled it for now. You will have to force-refresh your page (Ctrl-F5) to get the working version.
