### ISSUE TITLE
Rig Changes

### ISSUE THREAD

**Issue by jlatour88** [osmium-org/osmium#89]
If im correct, Rigs have been changed to allow you to use them without certain skills. For instance i was able to fit a Tech II Missile rig without any missile rig skill level. From what iv heard you just take the full penalty of the drawbacks. Or maybe u can fit them but they do nothing without the skill. Something to look into to update on the site.
Great site by the way, best one iv used and is primary for my fitting needs.

**Comment by Artefact2** [comment]
Fixed in a8fddb9ff11949189bce97b6608705f99aad31a2.
