### ISSUE TITLE
Hangs on initiating the awesome on import

### ISSUE THREAD

**Issue by JimMcClendon** [osmium-org/osmium#94]
this is the url https://o.smium.org/new/2789509502733385728

**Comment by Artefact2** [comment]
Hi Jim,

Can you reproduce the issue from a blank new loadout?

**Comment by wilson** [comment]
I am experiencing the same thing. I can reproduce it from a pretty 'blank' loadout in the following way:

* Click on 'Import'
* Leave it on 'Autodetect'
* Select 'Immediately edit the first loadout'
* Paste the following loadout skeleton:

```
[Pilgrim, Testgrim]

Liquid Ozone x500
```

..gives me the 'please report an issue' screen reliably. Waiting several minutes never causes it to finish loading: [Screenshot of import](http://puu.sh/gSrAS/7a5b904542.png)

Here is an existing import I have been trying to edit (to set scripts in the sensor boosters) if you want a 'live' example: [Unfinished Pilgrim](https://o.smium.org/loadout/private/25737/7163995025842372608)

**Comment by wilson** [comment]
I just tried importing the same ship as I first did, with none of the cargo hold items, and it seems to work fine. Possibly something related to that?

**Comment by Artefact2** [comment]
Fixed in aea6c983f78cf41fdf25feed04de55f68f3e82d4 and 78d81fadfb3cc0ee17eb4a415719d909f34acd90. Thanks for reporting this issue!

The bug affected fittings with non-fittable types (like cargo items) imported after the Scylla update.
