### ISSUE TITLE
Please add or highlight how to copy fit in EFT format

### ISSUE THREAD

**Issue by matticusrex** [osmium-org/osmium#98]
I just spent 5 minutes looking at a fit trying to figure out how to export it in some meaningful way.  If this feature exists please make it more visible.

To elaborate:  I was linked to this page (https://o.smium.org/loadout/11481) from reddit.com/r/fittings, I want to see what that ship's tracking graph looks like so I tried to find a way to export it to pyfa to load up a graph, but could not find an export option.

**Comment by Artefact2** [comment]
Please see #74.
