### ISSUE TITLE
Ancillary Armor Reppers Cap Usage

### ISSUE THREAD

**Issue by Dsfire** [osmium-org/osmium#99]
When you use an ancillary armor repairer and have it equipped with a charge. It will show incorrect capacitor stability and usage for the ship. It shows the correct usage when the reppers do not have charges equipped which leads me to believe that the code surrounding them are related to ancillary shield boosters.

Here is are images with charges and without charges
![with charge](https://cloud.githubusercontent.com/assets/10181869/7210868/66e1691e-e523-11e4-9760-46a0e314c9a7.png)
![without charge](https://cloud.githubusercontent.com/assets/10181869/7210869/66e2973a-e523-11e4-8389-7d42b7be1ec5.png)

.

**Comment by Artefact2** [comment]
Not a bug. When you use charges in the AAR, the capacitor simulation takes reloading times into account. If you disable reload times, you get the same result.
